# Generated by Django 4.2.27 on 2025-12-17 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botusers', '0001_initial'),
        ('dictionaries', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SCHOOL', 'School'), ('INSTRUCTOR', 'Instructor'), ('TESTS', 'Tests')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='NEW', max_length=20)),
                ('language', models.CharField(max_length=2)),
                ('main_intent', models.CharField(blank=True, choices=[('NO_LICENSE', 'No license'), ('REFRESH', 'Refresh'), ('CERT_NOT_PASSED', 'Cert not passed')], max_length=30, null=True)),
                ('tariff_price_kzt', models.IntegerField(blank=True, null=True)),
                ('gearbox', models.CharField(blank=True, max_length=10, null=True)),
                ('preferred_instructor_gender', models.CharField(blank=True, max_length=1, null=True)),
                ('has_driver_license', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('iin', models.CharField(blank=True, max_length=12, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(default='telegram_bot', max_length=50)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botusers.botuser')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.city')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.instructor')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.school')),
                ('tariff_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.tariffplan')),
                ('training_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.trainingformat')),
            ],
            options={
                'db_table': 'lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_status_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['lead', 'changed_at'], name='lead_status_lead_id_99b7c7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='lead_status_7af824_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['type', 'created_at'], name='lead_type_0e657a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['school', 'status', 'created_at'], name='lead_school__5dadf5_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['city', 'created_at'], name='lead_city_id_ba7fef_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='lead_phone_168f8e_idx'),
        ),
    ]
