# Generated by Django 4.2.27 on 2025-12-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
