# Generated by Django 4.2.27 on 2025-12-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_instructor_price_kzt_instructor_categories_and_more'),
        ('leads', '0002_lead_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='instructor_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.instructortariff'),
        ),
        migrations.AddField(
            model_name='lead',
            name='instructor_tariff_price_kzt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
