# Generated by Django 4.2.27 on 2026-01-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_training_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='tariff_plan',
        ),
        migrations.AddField(
            model_name='lead',
            name='tariff_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название тарифа'),
        ),
    ]
