# Generated by Django 4.2.27 on 2025-12-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='scope',
            field=models.CharField(choices=[('SCHOOL_CLIENT_MESSAGE', 'School client'), ('INSTRUCTOR_CLIENT_MESSAGE', 'Instructor client'), ('TESTS_OWNER_MESSAGE', 'Tests owner')], max_length=50),
        ),
    ]
