# Generated by Django 4.2.27 on 2026-01-08 17:13

from django.db import migrations, models


def create_gearbox_data(apps, schema_editor):
    """Создание данных для Gearbox"""
    Gearbox = apps.get_model('dictionaries', 'Gearbox')
    Gearbox.objects.get_or_create(
        code='AT',
        defaults={
            'name_ru': 'Автомат',
            'name_kz': 'Автомат',
            'is_active': True,
            'sort_order': 1
        }
    )
    Gearbox.objects.get_or_create(
        code='MT',
        defaults={
            'name_ru': 'Механика',
            'name_kz': 'Механика',
            'is_active': True,
            'sort_order': 2
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_trainingtimeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_kz', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dict_gearbox',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='dict_gearbo_is_acti_c1a2ec_idx')],
            },
        ),
        migrations.RunPython(
            code=create_gearbox_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
