# Generated by Django 4.2.27 on 2026-01-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_add_gearbox_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_tests',
            field=models.BooleanField(default=True),
        ),
    ]
