# Generated by Django 4.2.27 on 2025-12-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255)),
                ('name_kz', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('trust_index', models.IntegerField(default=0)),
                ('address_ru', models.CharField(max_length=255)),
                ('address_kz', models.CharField(max_length=255)),
                ('nearest_intake_date', models.DateField(blank=True, null=True)),
                ('nearest_intake_text_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_intake_text_kz', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.city')),
            ],
            options={
                'db_table': 'school',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('gearbox', models.CharField(choices=[('AT', 'Automatic'), ('MT', 'Manual')], max_length=10)),
                ('price_kzt', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('bio_ru', models.TextField(blank=True, null=True)),
                ('bio_kz', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.city')),
            ],
            options={
                'db_table': 'instructor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_kzt', models.IntegerField()),
                ('currency', models.CharField(default='KZT', max_length=3)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_kz', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='catalog.school')),
                ('tariff_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.tariffplan')),
            ],
            options={
                'db_table': 'school_tariff',
                'indexes': [models.Index(fields=['school', 'is_active'], name='school_tari_school__c1244d_idx')],
                'unique_together': {('school', 'tariff_plan')},
            },
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['city', 'is_active'], name='school_city_id_4dc36c_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['rating'], name='school_rating_977f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['city', 'gearbox', 'gender', 'is_active'], name='instructor_city_id_62081e_idx'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['rating'], name='instructor_rating_5f7051_idx'),
        ),
    ]
