# Generated by Django 4.2.27 on 2025-12-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='price_kzt',
        ),
        migrations.AddField(
            model_name='instructor',
            name='categories',
            field=models.ManyToManyField(related_name='instructors', to='dictionaries.category'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='description_kz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='trust_index_text_kz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='trust_index_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='InstructorTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_type', models.CharField(choices=[('SINGLE_HOUR', '1 час'), ('AUTODROM', 'Автодром'), ('PACKAGE_5', '5 вождений'), ('PACKAGE_10', '10 вождений'), ('PACKAGE_15', '15 вождений')], max_length=20)),
                ('price_kzt', models.IntegerField()),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_kz', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='catalog.instructor')),
            ],
            options={
                'db_table': 'instructor_tariff',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['instructor', 'is_active', 'sort_order'], name='instructor__instruc_8e6e21_idx')],
            },
        ),
    ]
