# Generated by Django 4.2.27 on 2026-01-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_schooltariff_school_tari_categor_b6bec0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltariff',
            name='gearbox',
            field=models.CharField(blank=True, choices=[('AT', 'Automatic'), ('MT', 'Manual')], max_length=10, null=True),
        ),
    ]
