# Generated by Django 4.2.27 on 2026-01-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_trainingtimeslot'),
        ('catalog', '0007_alter_schooltariff_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schooltariff',
            unique_together={('school', 'tariff_plan', 'training_format')},
        ),
    ]
