# Generated by Django 4.2.27 on 2026-01-08 17:13

from django.db import migrations, models
from django.db.models import Min, Count


def remove_duplicates_before_unique_constraint(apps, schema_editor):
    """Удаляет дубликаты перед применением уникального ограничения"""
    SchoolTariff = apps.get_model('catalog', 'SchoolTariff')
    
    # Находим группы с дубликатами по (school, tariff_plan, training_format)
    duplicate_groups = SchoolTariff.objects.values(
        'school', 'tariff_plan', 'training_format'
    ).annotate(
        count=Count('id'),
        min_id=Min('id')
    ).filter(count__gt=1)
    
    # Для каждой группы дубликатов оставляем только запись с минимальным ID
    for group in duplicate_groups:
        # Удаляем все записи с такой же комбинацией, кроме той, что с минимальным ID
        SchoolTariff.objects.filter(
            school_id=group['school'],
            tariff_plan_id=group['tariff_plan'],
            training_format_id=group['training_format']
        ).exclude(id=group['min_id']).delete()


def migrate_gearbox_data(apps, schema_editor):
    """Перенос данных из старого поля gearbox в ManyToManyField gearboxes"""
    SchoolTariff = apps.get_model('catalog', 'SchoolTariff')
    Gearbox = apps.get_model('dictionaries', 'Gearbox')
    
    # Получаем объекты Gearbox
    gearbox_at = Gearbox.objects.filter(code='AT').first()
    gearbox_mt = Gearbox.objects.filter(code='MT').first()
    
    if not gearbox_at or not gearbox_mt:
        return
    
    # Переносим данные из старого поля
    for tariff in SchoolTariff.objects.all():
        old_gearbox = tariff.gearbox
        if old_gearbox == 'AT':
            tariff.gearboxes.add(gearbox_at)
        elif old_gearbox == 'MT':
            tariff.gearboxes.add(gearbox_mt)


def reverse_migrate_gearbox_data(apps, schema_editor):
    """Обратная миграция - не реализована, так как поле gearbox будет удалено"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_add_gearbox_model'),
        ('catalog', '0009_alter_schooltariff_unique_together'),
    ]

    operations = [
        migrations.RunPython(
            code=remove_duplicates_before_unique_constraint,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='schooltariff',
            unique_together={('school', 'tariff_plan', 'training_format')},
        ),
        migrations.AddField(
            model_name='schooltariff',
            name='gearboxes',
            field=models.ManyToManyField(blank=True, related_name='tariffs', to='dictionaries.gearbox'),
        ),
        migrations.RunPython(
            code=migrate_gearbox_data,
            reverse_code=reverse_migrate_gearbox_data,
        ),
        migrations.RemoveField(
            model_name='schooltariff',
            name='gearbox',
        ),
    ]
