# Generated by Django 4.2.27 on 2026-01-08 18:04

from django.db import migrations, models


def migrate_tariff_plan_to_name(apps, schema_editor):
    """Перенос данных из tariff_plan.name_ru в tariff_name"""
    SchoolTariff = apps.get_model('catalog', 'SchoolTariff')
    TariffPlan = apps.get_model('dictionaries', 'TariffPlan')
    
    for tariff in SchoolTariff.objects.all():
        if tariff.tariff_plan_id:
            try:
                tariff_plan = TariffPlan.objects.get(id=tariff.tariff_plan_id)
                # Используем name_ru как название тарифа
                tariff.tariff_name = tariff_plan.name_ru
                tariff.save(update_fields=['tariff_name'])
            except TariffPlan.DoesNotExist:
                # Если tariff_plan не найден, используем код как fallback
                tariff.tariff_name = f"Tariff-{tariff.tariff_plan_id}"
                tariff.save(update_fields=['tariff_name'])


def reverse_migrate_tariff_name_to_plan(apps, schema_editor):
    """Обратная миграция - не реализована, так как поле tariff_plan будет удалено"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_add_gearbox_model'),
        ('catalog', '0010_change_gearbox_to_manytomany'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schooltariff',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schooltariff',
            name='tariff_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название тарифа'),
        ),
        migrations.RunPython(
            code=migrate_tariff_plan_to_name,
            reverse_code=reverse_migrate_tariff_name_to_plan,
        ),
        migrations.AlterField(
            model_name='schooltariff',
            name='tariff_name',
            field=models.CharField(max_length=255, verbose_name='Название тарифа'),
        ),
        migrations.AlterUniqueTogether(
            name='schooltariff',
            unique_together={('school', 'tariff_name', 'training_format')},
        ),
        migrations.RemoveField(
            model_name='schooltariff',
            name='tariff_plan',
        ),
    ]
