# Generated by Django 4.2.27 on 2025-12-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botusers', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botusers.botuser')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_name', 'created_at'], name='analytics_e_event_n_0a0c8f_idx'), models.Index(fields=['bot_user', 'created_at'], name='analytics_e_bot_use_866fa8_idx'), models.Index(fields=['lead', 'created_at'], name='analytics_e_lead_id_a2a15f_idx')],
            },
        ),
    ]
